spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart_api?createDatabaseIfNotExist=true
    username: root
    password: "yes"
  jpa:
    show-sql: true